n_points: 1024
seed: 42

train_data:
  size: 65536
  path: data/train
  jitter: 0.02

test_data:
  path: data/test

valid_data:
  split: 0.2

train:
  epochs: 15
  path: data/pointnet
  best_model_path: mlruns/358861021519665424/c0d7eb90a98347a69e4be684aef45a69/artifacts/epoch=14-step=7680/epoch=14-step=7680.ckpt
